name: dl-project
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Modificare a seconda del target
  - ffmpeg
  # Add other conda packages here
  - pip:
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - pyyaml
      - tensorboard
      - tqdm
      - timm
      - librosa
      - soundfile
      - einops
      - wandb
      # Add other pip-only packages here
